modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPLv3"
issueTrackerURL = "https://github.com/DavidQF555/SocrafticMethod/issues"
[[mods]]
modId = "socraftic_method"
version = "${file.jarVersion}"
displayName = "Socraftic Method"
displayURL = "https://github.com/DavidQF555/SocrafticMethod"
logoFile = "logo.png"
authors = "DavidQF555"
description = 'This mod adds philosophical features.'
[[dependencies.socraftic_method]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.socraftic_method]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
